config/routes.rb
Rails.application.routes.draw do
  resources :question_answers
  resources :quizzes
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question_answer.rb
class QuestionAnswer < ApplicationRecord
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_many :question_answers

  validates_uniqueness_of :token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/question_answers_controller.rb
class QuestionAnswersController < ApplicationController
  before_action :set_question_answer, only: [:show, :edit, :update, :destroy]

  # GET /question_answers
  # GET /question_answers.json
  def index
    @question_answers = QuestionAnswer.all
  end

  # GET /question_answers/1
  # GET /question_answers/1.json
  def show
  end

  # GET /question_answers/new
  def new
    @question_answer = QuestionAnswer.new
  end

  # GET /question_answers/1/edit
  def edit
  end

  # POST /question_answers
  # POST /question_answers.json
  def create
    @question_answer = QuestionAnswer.new(question_answer_params)

    respond_to do |format|
      if @question_answer.save
        format.html { redirect_to @question_answer, notice: 'Question answer was successfully created.' }
        format.json { render :show, status: :created, location: @question_answer }
      else
        format.html { render :new }
        format.json { render json: @question_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_answers/1
  # PATCH/PUT /question_answers/1.json
  def update
    respond_to do |format|
      if @question_answer.update(question_answer_params)
        format.html { redirect_to @question_answer, notice: 'Question answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_answer }
      else
        format.html { render :edit }
        format.json { render json: @question_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_answers/1
  # DELETE /question_answers/1.json
  def destroy
    @question_answer.destroy
    respond_to do |format|
      format.html { redirect_to question_answers_url, notice: 'Question answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_answer
      @question_answer = QuestionAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_answer_params
      params.require(:question_answer).permit(:question, :answer, :hide_answer, :quiz_id)
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
    respond_to do |format|
      format.html { @quiz }
      format.json { render :json => @quiz.to_json( :only => [:id, :token], include: {question_answers: {only: [:id, :question, :answer, :hide_answer]}} ) }
    end
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find_by(token: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_answers_helper.rb
module QuestionAnswersHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/home/index.html.erb
<div id='container'>
  <router-view></router-view>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hwquiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/question_answers/_form.html.erb
<%= form_with(model: question_answer, local: true) do |form| %>
  <% if question_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question_answer.errors.count, "error") %> prohibited this question_answer from being saved:</h2>

      <ul>
      <% question_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer %>
  </div>

  <div class="field">
    <%= form.label :hide_answer %>
    <%= form.check_box :hide_answer %>
  </div>

  <div class="field">
    <%= form.label :quiz_id %>
    <%= form.text_field :quiz_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/question_answers/edit.html.erb
<h1>Editing Question Answer</h1>

<%= render 'form', question_answer: @question_answer %>

<%= link_to 'Show', @question_answer %> |
<%= link_to 'Back', question_answers_path %>

app/views/question_answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Question Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Hide answer</th>
      <th>Quiz</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_answers.each do |question_answer| %>
      <tr>
        <td><%= question_answer.question %></td>
        <td><%= question_answer.answer %></td>
        <td><%= question_answer.hide_answer %></td>
        <td><%= question_answer.quiz %></td>
        <td><%= link_to 'Show', question_answer %></td>
        <td><%= link_to 'Edit', edit_question_answer_path(question_answer) %></td>
        <td><%= link_to 'Destroy', question_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question Answer', new_question_answer_path %>

app/views/question_answers/new.html.erb
<h1>New Question Answer</h1>

<%= render 'form', question_answer: @question_answer %>

<%= link_to 'Back', question_answers_path %>

app/views/question_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question_answer.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question_answer.answer %>
</p>

<p>
  <strong>Hide answer:</strong>
  <%= @question_answer.hide_answer %>
</p>

<p>
  <strong>Quiz:</strong>
  <%= @question_answer.quiz %>
</p>

<%= link_to 'Edit', edit_question_answer_path(@question_answer) %> |
<%= link_to 'Back', question_answers_path %>

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, local: true) do |form| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.token %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @quiz.token %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>